[package]
name = "dns"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
log = "0.4"
tokio = { version = "1", features = ["full"] }


[dev-dependencies]
tokio-test = "0.4.4"  # Add this line
test-log = "0.2.16"
